(in-package :innate.types)

;;; Node kind constants
;;; Each constant holds its own keyword value — safe for defconstant because
;;; keywords are self-evaluating and EQL-comparable across image reloads.

(defconstant +node-program+     :program)
(defconstant +node-bracket+     :bracket)
(defconstant +node-agent+       :agent)
(defconstant +node-bundle+      :bundle)
(defconstant +node-reference+   :reference)
(defconstant +node-search+      :search)
(defconstant +node-fulfillment+ :fulfillment)
(defconstant +node-emission+    :emission)
(defconstant +node-decree+      :decree)
(defconstant +node-wikilink+    :wikilink)
(defconstant +node-combinator+  :combinator)
(defconstant +node-lens+        :lens)
(defconstant +node-kv-pair+     :kv-pair)
(defconstant +node-modifier+    :modifier)
(defconstant +node-prose+       :prose)
(defconstant +node-heading+     :heading)
(defconstant +node-string-lit+  :string-lit)
(defconstant +node-number-lit+  :number-lit)
(defconstant +node-bare-word+   :bare-word)
(defconstant +node-emoji-slot+  :emoji-slot)

;;; Universal AST node struct
;;; Dispatch on (node-kind n) using etypecase in the evaluator.
;;; Adding a new node kind requires zero struct changes — only a new constant above.

(defstruct (node (:constructor make-node (&key kind value children props)))
  "Universal AST node. Dispatch on (node-kind n) using etypecase.
  kind     — keyword constant from +node-*+ set
  value    — primary value (string, number, or nil)
  children — list of child nodes (nil = leaf)
  props    — plist of kind-specific properties"
  (kind     nil)
  (value    nil)
  (children nil)
  (props    nil))

;;; Result types

(defstruct (innate-result (:constructor make-innate-result (&key value context)))
  "Successful evaluation result.
  value   — the computed value
  context — evaluation mode: :query :scope :render :commission"
  (value   nil)
  (context nil))

(defstruct (resistance (:constructor make-resistance (&key message source)))
  "A resolution failure value. Returned by the evaluator, not signaled.
  Distinct from innate-resistance condition which is signaled up the call stack.
  resistance-p predicate is auto-generated by defstruct.
  message — human-readable description of what failed
  source  — the expression string that could not be resolved"
  (message "" :type string)
  (source  "" :type string))
